// Generated by CoffeeScript 1.8.0
(function() {
  this.Price = (function() {
    function Price(net, tax, rate, country, company) {
      this.net = net;
      this.tax = tax;
      this.rate = rate;
      this.country = country;
      this.company = company;
    }

    Price.prototype.getNetValue = function() {
      return this.net;
    };

    Price.prototype.getValue = function() {
      return this.net + this.tax;
    };

    Price.prototype.getTax = function() {
      return this.tax;
    };

    Price.prototype.getTaxRate = function() {
      return this.rate;
    };

    Price.prototype.getCountry = function() {
      return this.country;
    };

    Price.prototype.isCompany = function() {
      return this.company;
    };

    return Price;

  })();

}).call(this);
