// Generated by CoffeeScript 1.8.0
(function() {
  this.RuleSet = (function() {
    function RuleSet() {
      this.rules = {};
    }

    RuleSet.prototype.addRule = function(rule) {
      return this.rules[rule.identifier()] = rule.value();
    };

    RuleSet.prototype.hasRule = function(identifier) {
      var id;
      for (id in this.rules) {
        if (id === identifier) {
          return true;
        }
      }
      return false;
    };

    RuleSet.prototype.getRuleValue = function(identifier) {
      var id, value, _ref;
      _ref = this.rules;
      for (id in _ref) {
        value = _ref[id];
        if (id === identifier) {
          return this.rules[id];
        }
      }
      return null;
    };

    return RuleSet;

  })();

}).call(this);
