// Generated by CoffeeScript 1.8.0
(function() {
  this.Rule = (function() {
    function Rule(id, val) {
      this.id = id;
      this.val = val;
    }

    Rule.prototype.identifier = function() {
      return this.id;
    };

    Rule.prototype.value = function() {
      return this.val;
    };

    return Rule;

  })();

}).call(this);
